// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NodeManagement_SendRequest_FullMethodName = "/hw04.NodeManagement/sendRequest"
)

// NodeManagementClient is the client API for NodeManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeManagementClient interface {
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type nodeManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeManagementClient(cc grpc.ClientConnInterface) NodeManagementClient {
	return &nodeManagementClient{cc}
}

func (c *nodeManagementClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, NodeManagement_SendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeManagementServer is the server API for NodeManagement service.
// All implementations must embed UnimplementedNodeManagementServer
// for forward compatibility
type NodeManagementServer interface {
	SendRequest(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedNodeManagementServer()
}

// UnimplementedNodeManagementServer must be embedded to have forward compatible implementations.
type UnimplementedNodeManagementServer struct {
}

func (UnimplementedNodeManagementServer) SendRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedNodeManagementServer) mustEmbedUnimplementedNodeManagementServer() {}

// UnsafeNodeManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeManagementServer will
// result in compilation errors.
type UnsafeNodeManagementServer interface {
	mustEmbedUnimplementedNodeManagementServer()
}

func RegisterNodeManagementServer(s grpc.ServiceRegistrar, srv NodeManagementServer) {
	s.RegisterService(&NodeManagement_ServiceDesc, srv)
}

func _NodeManagement_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagement_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeManagement_ServiceDesc is the grpc.ServiceDesc for NodeManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hw04.NodeManagement",
	HandlerType: (*NodeManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendRequest",
			Handler:    _NodeManagement_SendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
