// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsermanagementClient is the client API for Usermanagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsermanagementClient interface {
	SendMessage(ctx context.Context, in *PublishMessage, opts ...grpc.CallOption) (*Timestamp, error)
	RequestChange(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Timestamp, error)
	RequestBroadcast(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Broadcast, error)
	LeaveClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Confirmation, error)
	ClientJoin(ctx context.Context, in *NewClient, opts ...grpc.CallOption) (*Client, error)
}

type usermanagementClient struct {
	cc grpc.ClientConnInterface
}

func NewUsermanagementClient(cc grpc.ClientConnInterface) UsermanagementClient {
	return &usermanagementClient{cc}
}

func (c *usermanagementClient) SendMessage(ctx context.Context, in *PublishMessage, opts ...grpc.CallOption) (*Timestamp, error) {
	out := new(Timestamp)
	err := c.cc.Invoke(ctx, "/ChittyChat.Usermanagement/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usermanagementClient) RequestChange(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Timestamp, error) {
	out := new(Timestamp)
	err := c.cc.Invoke(ctx, "/ChittyChat.Usermanagement/RequestChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usermanagementClient) RequestBroadcast(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*Broadcast, error) {
	out := new(Broadcast)
	err := c.cc.Invoke(ctx, "/ChittyChat.Usermanagement/RequestBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usermanagementClient) LeaveClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, "/ChittyChat.Usermanagement/LeaveClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usermanagementClient) ClientJoin(ctx context.Context, in *NewClient, opts ...grpc.CallOption) (*Client, error) {
	out := new(Client)
	err := c.cc.Invoke(ctx, "/ChittyChat.Usermanagement/ClientJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsermanagementServer is the server API for Usermanagement service.
// All implementations must embed UnimplementedUsermanagementServer
// for forward compatibility
type UsermanagementServer interface {
	SendMessage(context.Context, *PublishMessage) (*Timestamp, error)
	RequestChange(context.Context, *Timestamp) (*Timestamp, error)
	RequestBroadcast(context.Context, *Timestamp) (*Broadcast, error)
	LeaveClient(context.Context, *Client) (*Confirmation, error)
	ClientJoin(context.Context, *NewClient) (*Client, error)
	mustEmbedUnimplementedUsermanagementServer()
}

// UnimplementedUsermanagementServer must be embedded to have forward compatible implementations.
type UnimplementedUsermanagementServer struct {
}

func (UnimplementedUsermanagementServer) SendMessage(context.Context, *PublishMessage) (*Timestamp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedUsermanagementServer) RequestChange(context.Context, *Timestamp) (*Timestamp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestChange not implemented")
}
func (UnimplementedUsermanagementServer) RequestBroadcast(context.Context, *Timestamp) (*Broadcast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestBroadcast not implemented")
}
func (UnimplementedUsermanagementServer) LeaveClient(context.Context, *Client) (*Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveClient not implemented")
}
func (UnimplementedUsermanagementServer) ClientJoin(context.Context, *NewClient) (*Client, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientJoin not implemented")
}
func (UnimplementedUsermanagementServer) mustEmbedUnimplementedUsermanagementServer() {}

// UnsafeUsermanagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsermanagementServer will
// result in compilation errors.
type UnsafeUsermanagementServer interface {
	mustEmbedUnimplementedUsermanagementServer()
}

func RegisterUsermanagementServer(s grpc.ServiceRegistrar, srv UsermanagementServer) {
	s.RegisterService(&Usermanagement_ServiceDesc, srv)
}

func _Usermanagement_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChat.Usermanagement/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).SendMessage(ctx, req.(*PublishMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usermanagement_RequestChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).RequestChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChat.Usermanagement/RequestChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).RequestChange(ctx, req.(*Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usermanagement_RequestBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).RequestBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChat.Usermanagement/RequestBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).RequestBroadcast(ctx, req.(*Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usermanagement_LeaveClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).LeaveClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChat.Usermanagement/LeaveClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).LeaveClient(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usermanagement_ClientJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).ClientJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChittyChat.Usermanagement/ClientJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).ClientJoin(ctx, req.(*NewClient))
	}
	return interceptor(ctx, in, info, handler)
}

// Usermanagement_ServiceDesc is the grpc.ServiceDesc for Usermanagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usermanagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChittyChat.Usermanagement",
	HandlerType: (*UsermanagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Usermanagement_SendMessage_Handler,
		},
		{
			MethodName: "RequestChange",
			Handler:    _Usermanagement_RequestChange_Handler,
		},
		{
			MethodName: "RequestBroadcast",
			Handler:    _Usermanagement_RequestBroadcast_Handler,
		},
		{
			MethodName: "LeaveClient",
			Handler:    _Usermanagement_LeaveClient_Handler,
		},
		{
			MethodName: "ClientJoin",
			Handler:    _Usermanagement_ClientJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
